name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: tst1
      id: tst1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: tst1
        setup-command: gcc hello.c -o hello
        command: "./hello"
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TST1_RESULTS: "${{steps.tst1.outputs.result}}"
      with:
        runners: tst1
